version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'

    groups:
      non-major-deps:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'

    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
